### PR TITLE
Display speeds in bits per second instead of KiB/s

### PR DESCRIPTION
**Pull request by vjr**
This is a patch to make the Network Monitor desktop plasmoid widget display the upload and download speeds in bits per second (Mbps, Kbps or bps as the case may be) rather than the fixed "KiB/s" unit.

It appears the input data is always in KiB units so the bps part may never be called but left it in there anyway.

### CODE REVIEW

**Comment by Zren** [comment]
GitHub is a source code mirror only for KDE.

You'll want to submit a new diff on https://phabricator.kde.org/differential/diff/create/

**Comment by davidedmundson** [comment]
It's now on phab.

**Comment by safinaskar** [comment]
(Sorry for spam. I was unable to upload this video to kde bugtracker, so here it is.)

[a.webm](https://github.com/user-attachments/assets/5616e874-45b6-4dd3-8a19-6b26cfd7f63e)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/KDE/plasma-workspace/pull/1#issuecomment-2576289257

@safinaskar, you could have just used YouTube. There's no guarantee that GitHub media upload URIs are stable.

**Pull request closed without merging**
